import Head from "next/head";
import Image from "next/image";
import HeaderNav from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {

  return (
    <div>
      <Head>
        <title>risa-movie-app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HeaderNav />
      <Navbar />
      <Results results= {results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTranding.url
    }`
  ).then(res => res.json())

  return {
    props: {
      results: request.results
    }
  }
}
